Category.create(name:"Appetizers")
Category.create(name:"Soups And Salads")
Category.create(name:"Main Course")
Category.create(name:"Desserts")


User.create({name: "Linse", password: "password", email: "blank1@blank.com", location: "Houma, Louisiana", about: "My favorite food is pizza."})
User.create({name: "Brandon", password: "password", email: "blank2@blank.com", location: "New York, New York", about: "I like all kinds of food. Please rate my recipes."})
User.create({name: "Caitlin", password: "password", email: "blank3@blank.com", location: "Seattle, Washington", about: "I like this website because it is about food."})
User.create({name: "Ron", password: "password", email: "blank4@blank.com", location: "Boston, Massachusetts", about: "Avid cook. I eat a tonne of meat every year."})
User.create({name: "Chet", password: "password", email: "blank5@blank.com", location: "Philadelphia, Pennsylvania", about: "I love this website. I collect recipes as a hobby."})
User.create({name: "Joe", password: "password", email: "blank6@blank.com", location: "Boston, Massachusetts", about: "I can't wait to try all these recipes out."})
User.create({name: "Matt", password: "password", email: "blank7@blank.com", location: "Philadelphia, Pennsylvania", about: "I can't cook, so I'm looking forward to using this site."})
User.create({name: "Linsey", password: "password", email: "blank8@blank.com", location: "Houma, Louisiana", about: "My favorite food is pizza."})
User.create({name: "Brandony", password: "password", email: "blank9@blank.com", location: "New York, New York", about: "I like all kinds of food. Please rate my recipes."})
User.create({name: "Caitliny", password: "password", email: "blank10@blank.com", location: "Seattle, Washington", about: "I like this website because it is about food."})
User.create({name: "Rony", password: "password", email: "blank11@blank.com", location: "Boston, Massachusetts", about: "Avid cook. I eat a tonne of meat every year."})
User.create({name: "Chety", password: "password", email: "blank12@blank.com", location: "Philadelphia, Pennsylvania", about: "I love this website. I collect recipes as a hobby."})
User.create({name: "Joey", password: "password", email: "blank13@blank.com", location: "Boston, Massachusetts", about: "I can't wait to try all these recipes out."})
User.create({name: "Matty", password: "password", email: "blank14@blank.com", location: "Philadelphia, Pennsylvania", about: "I can't cook, so I'm looking forward to using this site."})


Ingredient.create(name: "Salt")
Ingredient.create(name: "Pepper")
Ingredient.create(name: "Mushrooms")
Ingredient.create(name: "Cheese")
Ingredient.create(name: "Tomatoes")
Ingredient.create(name: "Ham")
Ingredient.create(name: "Olives")
Ingredient.create(name: "Parsley")

Measurement.create(name: 'c')
Measurement.create(name: 'tsp')
Measurement.create(name: 'tbsp')
Measurement.create(name: 'package')
Measurement.create(name: 'oz')
Measurement.create(name: 'g')
Measurement.create(name: 'lb')
Measurement.create(name: 'kg')
Measurement.create(name: 'ml')
Measurement.create(name: 'L.')



Recipe.create({name: "10-Minute Energizing Oatmeal", difficulty_level: "Expert", prep_time_hours: 0, prep_time_min: 5, directions: "Bring the water and salt to a boil in a saucepan, then turn the heat to low and add the oats. Cook for about 5 minutes, stirring regularly so that the oatmeal will not clump together. Add cinnamon, raisins and almonds, stir, cover the pan and turn off heat. Let sit for 5 minutes. Serve with milk and sweetener.", description: "This is a delicious complete breakfast and a perfect way to start your day!", creator: "Grandma", servings: 4, category_id: 1, user_id: 1})

Recipe.create({name: "10-Minute Huevos Rancheros", difficulty_level: "Beginner", prep_time_hours: 0, prep_time_min: 20, directions: "Poach eggs. Heat beans in a skillet while eggs are cooking. Remove beans from heat and mix in olive oil, lemon juice, salt and pepper Add a pinch of cayenne for spicy beans. Place beans on plate, top with poached eggs, avocado, salsa, cheese and cilantro.", description: "Huevos rancheros don't have to take a long time to prepare. Try this easy-to-prepare version for a breakfast treat you can make on a work day!", creator: "Grandma", servings: 4, category_id: 1, user_id: 2})

Recipe.create({name: "Any Time Frittata", difficulty_level: "Intermediate", prep_time_hours: 0, prep_time_min: 30, directions: "Chop onions and garlic and let sit for at least 5 minutes to enhance their health-promoting properties. Beat together eggs, egg whites, turmeric, and a pinch of salt and pepper. Set aside. Heat 1 TBS broth in 10-12 inch stainless steel skillet. Healthy Sauté onion, garlic, and green chili for about 3 minutes stirring frequently. After 3 minutes, add zucchini, tomato, cilantro, salt, and pepper to zucchini mixture. Pour egg mixture over vegetables. Turn heat to low and cover. Cook for about 10 minutes checking periodically to see if eggs are firm. When done, run a rubber spatula around edge of frittata, cut into four wedges and serve.", description: "Don't reserve this great frittata for breakfast; it's wonderful for lunch or dinner as well! Zucchini and tomatoes provide excellent sources of health-promoting nutrients to your Healthiest Way of Eating. And you get all of this for only 85 calories!", creator: "Grandma", servings: 4, category_id: 1, user_id: 3})

Recipe.create({name: "Breakfast Bagel", difficulty_level: "Expert", prep_time_hours:3, prep_time_min: 40, directions: "Bring water and 1 tsp vinegar to a light boil in a shallow pan. Make sure there is enough water to cover egg. While water is coming to a boil, slice bagel in half and toast. Place tomato, avocado, and cheese on top of toasted bagel. ", description: "This healthy version of an egg sandwich is a great addition to your Healthiest Way of Eating any time of day. It not only tastes great but provides a rich source of manganese, vitamin K and protein among other nutrients. Enjoy!", creator: "My Great-Great-Aunt", servings: 4, category_id: 1, user_id: 4})

Recipe.create({name: "Granola with Fresh Fruit", difficulty_level: "Expert", prep_time_hours: 1, prep_time_min: 10, directions: "Granola is a favorite healthy breakfast for many. Adding the fruit and sliced almonds makes this a special treat with extra nutrition that will sustain you for hours, and it can be done in just 10 minutes.This tastes good", description: "Divide granola into 4 bowls. Top with fruit and milk.", creator: "Cousin, twice-removed", servings: 4, category_id: 1, user_id: 5})

Recipe.create({name: "Healthy Breakfast Frittata", difficulty_level: "Beginner", prep_time_hours: 0, prep_time_min: 25, directions: "Mince onion and chop garlic let them sit for 5 minutes to enhance their health-promoting benefits. Preheat broiler on low. Heat 1 TBS broth in a 9-10 inch stainless steel skillet. Healthy Sauté onion over medium heat, for about 3 minutes, stirring often. Add garlic, ground lamb or turkey, and cook for another 3 minutes on medium heat, breaking up clumps. Add kale and 2 TBS broth. Reduce heat to low and continue to cook covered for about 5 more minutes. Season with salt and pepper, and mix. Beat eggs, season with a pinch of salt and pepper, and pour on top of mixture evenly. Cook on low for another 2 minutes without stirring. Place skillet under broiler in middle of oven, about 7 inches from the heat source so it has time to cook without the top burning. As soon as the eggs are firm, it is done, about 2-3 minutes. Mince onion and chop garlic let them sit for 5 minutes to enhance their health-promoting benefits. Preheat broiler on low. Heat 1 TBS broth in a 9-10 inch stainless steel skillet. Healthy Sauté onion over medium heat, for about 3 minutes, stirring often. Add garlic, ground lamb or turkey, and cook for another 3 minutes on medium heat, breaking up clumps. Add kale and 2 TBS broth. Reduce heat to low and continue to cook covered for about 5 more minutes. Season with salt and pepper, and mix. Beat eggs, season with a pinch of salt and pepper, and pour on top of mixture evenly. Cook on low for another 2 minutes without stirring. Place skillet under broiler in middle of oven, about 7 inches from the heat source so it has time to cook without the top burning. As soon as the eggs are firm, it is done, about 2-3 minutes.", description: "Enjoy this tasty frittata recipe any time of the day. Serve with a large salad for a complete meal.", creator: "Neighbor", servings: 4, category_id: 1, user_id: 6})

Recipe.create({name: "Healthy Lifestyle Tea", difficulty_level: "Beginner", prep_time_hours: 0, prep_time_min: 10, directions: "Green tea is not only delicious but is renowned for its health-promoting properties. These have been linked to hits high concentration of catechin phytonutrients, which have a wide variety of protetive benefits, many related to their potent ability to fight free radicals. Adding 1 tsp lemon juice per cup of green tea not only gives it a refreshing taste but additional health benefits; it is both cleansing and energizing.", description: "The phytonutrients found in green tea help combat free radicals and provide a wide variety of health protective benefits.his tastes good", creator: "my boss", servings: 4, category_id: 1, user_id: 7})

Recipe.create({name: "5 Spice Onion Soup", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "To prepare onion broth, heat 1 TBS chicken or vegetable broth in medium soup pot. Healthy Sauté chopped onion over medium heat for 5 minutes, stirring frequently, until translucent. Add 6 cups of chicken or vegetable broth and remaining onion broth ingredients and stir. Bring to a boil, reduce heat to medium low, and simmer ingredients briskly together for 20 minutes, uncovered. This will bring out a lot of flavor from the ingredients.", description: "This Asian-flavored onion soup is a great tasting addition to your Healthiest Way of Eating. It combines onions with shiitake mushrooms for a delicious and unique flavor experience. Enjoy!", creator: "Mother Dearest", servings: 4, category_id: 2, user_id: 1})

Recipe.create({name: "5-Minute Miso Soup with Dulse", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Add miso, ginger, and dulse to 1 cup of boiling water.", description: "Add this quick and easy miso soup to your Healthiest Way of Eating and give your body an extra boost of health-promoting minerals. Feel free to add other seaweed such as wakame for extra nutrition.", creator: "Mother Dearest", servings: 4, category_id: 2, user_id: 2})

Recipe.create({name: "Barley Mushroom Soup", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Add rest of broth and bring soup to a boil on high heat. Once it comes to a boil, reduce heat to medium and simmer for about 40 minutes, or until barley and carrots are tender. Add mushrooms and continue to sauté for another 3 minutes. Add drained barley and Tawny Port and cook for about 2 minutes. Heat 1 TBS broth in a medium soup pot. Healthy Sauté onion, garlic, and carrots in broth for 5 minutes over medium heat, stirring frequently.", description: "The crimini mushrooms and tawny port gives this Barley Mushroom Soup extra flavor. This soup is a great way to enjoy the health benefits of barley.", creator: "Mother Dearest", servings: 4, category_id: 2, user_id: 3})

Recipe.create({name: "Carrot Coconut Soup", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Blend in batches making sure blender is not more than half full. When it's hot, and the blender is too full, it can erupt and burn you. Add salt and pepper to taste. Add broth, carrots, and sweet potato and simmer on medium high heat until vegetables are tender, about 15 minutes. Heat 1 TBS broth in a medium soup pot. Healthy Sauté onion in broth over medium heat for about 5 minutes, stirring often.", description: "The ginger and curry powder add great flavor to this easy-to-prepare soup. It's also rich in vitamin A and tastes great!", creator: "Mother Dearest", servings: 4, category_id: 2, user_id: 4})

Recipe.create({name: "Golden Squash Soup", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Place in blender and blend with coconut milk. Make sure you blend in batches filling blender only half full. Start on low speed, so hot soup does not erupt and burn you. Blend until smooth, about 1 minute. Thin with a little broth if needed. Season to taste with salt and white pepper. Reheat, and add cilantro. Add garlic and ginger, and continue to sauté for another minute. Add turmeric and curry powder, and mix well. Add squash and broth, and mix. Bring to a boil on high heat. Once it comes to a boil reduce heat to medium-low and simmer uncovered until squash is tender, about 10 minutes.", description: "This easy-to-prepare soup is a favorite among many of our readers. It's not only flavorful, but an excellent source of vitamin A. Enjoy!", creator: "Mother Dearest", servings: 4, category_id: 2, user_id: 5})

Recipe.create({name: "15-Minute Broiled Chicken Salad", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "When pan is hot, season chicken breasts with a little salt and pepper and place on hot pan skin side up. Return to broiler and cook for about 15 minutes, or until done, depending on the thickness of the breasts. The breasts cook fast because they are cooking on both sides at the same time. This is our Quick Broil cooking method. When chicken is just about done, remove skin and top breasts with a little gorgonzola cheese and return to broiler to melt. (If you're not sure if chicken is done, make a little slice with a small sharp knife to check. It should be only slightly pink.)", description: "This quick and easy chicken salad is a perfect lunch or light dinner, making it easy for you to enjoy a great tasting way to receive the health benefits of chicken and salad greens. Our Quick Broil method of cooking helps seal in the chicken's juices making it more tender and flavorful. Feel free to add your favorite vegetables to for extra nutrition.", creator: "Mother Dearest", servings: 4, category_id: 3, user_id: 6})

Recipe.create({name: "15-Minute Healthy Sautéed Chicken & Asparagus", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Add asparagus, soy sauce, vinegar, and red chili flakes. Stir together and cover. Cook for another 2-3 minutes. This may have to cook for an extra couple minutes if the asparagus is thick. Season with salt and pepper to taste. Add ginger, garlic, chicken, and continue to Healthy Sauté for another 3-4 minutes, stirring constantly.", description: "The chicken and asparagus combination in this recipe is a wonderful addition to your Healthiest Way of Eating. It not only tastes great but contains just 275 calories!", creator: "Mother Dearest", servings: 4, category_id: 3, user_id: 7})

Recipe.create({name: "10-Minute Rosemary Lamb Chops", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Preheat broiler on high heat, and place a stainless steel or cast iron skillet large enough to hold the lamb chops under the heat for about 10 minutes to get very hot (about 5-7 inches from the heat source). Be sure that the handle is also metal. Once pan is hot, place lamb chops in pan, and return to broiler for about 4-5 minutes, depending on thickness of lamb. Lamb is cooked quickly as it is cooking on both sides at the same time. This is our Quick Broil cooking method.", description: "Nothing complements the flavor of lamb better than rosemary. And our Quick Broil method makes this dish very fast and easy to prepare. With this dish you not only enjoy great taste but add an excellent source of protein, vitamin B12, selenium, zinc, and vitamin B3 to your Healthiest Way of Eating. Enjoy!", creator: "Mother Dearest", servings: 4, category_id: 3, user_id: 1})

Recipe.create({name: "Southwestern Salmon & Black Beans", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Place salmon in the hot pan and return to broiler about 5 inches from the heat source for best results. Broil salmon for about 7 minutes for medium doneness. This is our Quick Broil cooking method. Serve salmon, beans, lettuce and avocado together on a plate. Top salmon and lettuce with cilantro topping. While beans are cooking, preheat broiler. Place a stainless steel or cast iron skillet large enough for salmon under the heat to get hot. This takes about 10 minutes.", description: "Add this amazing flavor blend that combines the sweetness of the salmon, richness of black beans, and the zestiness of the topping to your Healthiest Way of Eating and enjoy!", creator: "Mother Dearest", servings: 4, category_id: 3, user_id: 2})

Recipe.create({name: "Salmon with Maple Dijon Glaze", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Preheat the broiler on high and place an all stainless steel skillet (be sure the handle is also stainless steel) or cast iron pan under the heat fro about 10 minutes to get it very hot. The pan should be 5-7 inches from the heat source. Using a hot pad,pull pan away from heat and place salmon on hot pan, skin side down. Return to broiler. Keep in mind that it is cooking rapidly on both sides, so it will be done very quickly.", description: "Add a tasty twist to our quick broiled Salmon with this easy-to-prepare glaze.", creator: "Mother Dearest", servings: 4, category_id: 3, user_id: 3})

Recipe.create({name: "Cranberry and Fresh Pear Cobbler", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Grate enough orange rind to make 1 tsp zest and place in a mixing bowl. Cut the orange in half and juice both halves into the same bowl as the rind. Add the cranberries and honey. Mix until the honey is dissolved. Let sit for 1/2 hour to allow cranberries to soften. After the cranberries have softened, cut the pear into 1/4-inch cubes and add to the bowl.", description: "This is a wonderful after-dinner treat that provides a great combination of flavors and health benefits to your Healthiest Way of Eating! Cranberries, like their cousin blueberries, are one of the best sources of health-promoting antioxidants.", creator: "Mother Dearest", servings: 4, category_id: 4, user_id: 4})

Recipe.create({name: "Blueberry Parfait", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Layer yogurt and blueberries in 2 wine glasses. Top with chopped walnuts. Sprinkle grated chocolate and diced crystallized ginger, if desired.", description: "You can make this easy-to-prepare recipe with blueberries or any one of your favorite fruits.", servings: 4, category_id: 4, user_id: 2})

Recipe.create({name: "Ginger Yogurt with Fruit", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Blend together yogurt, banana, and ginger in blender. Spoon out meat of papaya and divide papaya and grapes between two bowls. Mix with blended yogurt and top with sliced almonds.", description: "Enjoy the zing the ginger provides in this festive, delicious, and easy to prepare recipe. It is a great addition to your list of Healthiest Way of Eating desserts.", creator: "Mother Dearest", servings: 4, category_id: 4, user_id: 6})

Recipe.create({name: "Orange and Coconut Treat", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Prepare fruit and toss with coconut and almonds.", description: "Include a healthy bit of sweetness to your Healthiest Way of Eating with this easy-to-prepare recipe, which you can enjoy for breakfast or as a dessert or snack.", creator: "Mother Dearest", servings: 4, category_id: 4, user_id: 6})

Recipe.create({name: "Orange, Pineapple, Papaya Salad", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Cutting the orange segments as suggested in our preparation tip will eliminate the bitterness and rough texture of the membrane without the segments falling apart.", description: "This is a beautiful and refreshing fruit dish that takes only as much time as it takes to cut the fruit. And you can enjoy it as a salad or a dessert. Enjoy!", creator: "Mother Dearest", servings: 4, category_id: 4, user_id: 1})

Recipe.create({name: "Grapefruit Sunrise", difficulty_level: "Intermediate", prep_time_hours: 2, prep_time_min: 40, directions: "Place grapefruit juice, orange juice, 1 cup strawberries, and honey in blender and blend until smooth. Strain into 2 chilled glasses. Top with grapefruit sections and sliced strawberries.", description: "This delicious dessert adds sunshine sweetness to your Healthiest Way of Eating! And one serving provides 411% of the Daily Value (DV) for vitamin C, 26% DV for potassium and 26% DV for folate. Enjoy!", creator: "Mother Dearest", servings: 4, category_id: 4, user_id: 1})

RecipeIngredient.create(recipe_id: 1, ingredient_id: 1, measurement_id: 1, quantity: 2.0)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 2, measurement_id: 2, quantity: 2.0)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 3, measurement_id: 3, quantity: 2.0)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 2, measurement_id: 4, quantity: 3.0)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 4, measurement_id: 5, quantity: 3.0)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 3, measurement_id: 6, quantity: 3.0)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 5, measurement_id: 7, quantity: 4.0)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 4, measurement_id: 8, quantity: 4.0)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 1, measurement_id: 9, quantity: 4.0)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 3, measurement_id: 10, quantity: 5.0)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 4, measurement_id: 1, quantity: 5.0)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 2, measurement_id: 2, quantity: 5.0)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 4, measurement_id: 3, quantity: 2.0)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 5, measurement_id: 4, quantity: 2.0)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 1, measurement_id: 5, quantity: 2.0)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 2, measurement_id: 6, quantity: 2.0)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 5, measurement_id: 7, quantity: 2.0)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 4, measurement_id: 8, quantity: 2.0)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 2, measurement_id: 9, quantity: 2.0)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 3, measurement_id: 10, quantity: 2.0)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 1, measurement_id: 1, quantity: 2.0)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 1, measurement_id: 2, quantity: 2.0)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 2, measurement_id: 3, quantity: 2.0)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 3, measurement_id: 4, quantity: 2.0)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 2, measurement_id: 5, quantity: 3.0)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 4, measurement_id: 6, quantity: 3.0)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 3, measurement_id: 7, quantity: 3.0)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 5, measurement_id: 8, quantity: 4.0)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 4, measurement_id: 9, quantity: 4.0)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 1, measurement_id: 10, quantity: 4.0)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 3, measurement_id: 1, quantity: 5.0)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 4, measurement_id: 1, quantity: 5.0)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 2, measurement_id: 2, quantity: 5.0)
RecipeIngredient.create(recipe_id: 13, ingredient_id: 4, measurement_id: 3, quantity: 2.0)
RecipeIngredient.create(recipe_id: 13, ingredient_id: 5, measurement_id: 4, quantity: 2.0)
RecipeIngredient.create(recipe_id: 13, ingredient_id: 1, measurement_id: 5, quantity: 2.0)
RecipeIngredient.create(recipe_id: 14, ingredient_id: 2, measurement_id: 6, quantity: 2.0)
RecipeIngredient.create(recipe_id: 16, ingredient_id: 5, measurement_id: 7, quantity: 2.0)
RecipeIngredient.create(recipe_id: 16, ingredient_id: 4, measurement_id: 8, quantity: 2.0)
RecipeIngredient.create(recipe_id: 16, ingredient_id: 2, measurement_id: 9, quantity: 2.0)
RecipeIngredient.create(recipe_id: 17, ingredient_id: 3, measurement_id: 10, quantity: 1.0)
RecipeIngredient.create(recipe_id: 17, ingredient_id: 1, measurement_id: 1, quantity: 2.0)
RecipeIngredient.create(recipe_id: 17, ingredient_id: 3, measurement_id: 2, quantity: 3.0)
RecipeIngredient.create(recipe_id: 18, ingredient_id: 4, measurement_id: 3, quantity: 4.0)
RecipeIngredient.create(recipe_id: 18, ingredient_id: 2, measurement_id: 4, quantity: 5.0)
RecipeIngredient.create(recipe_id: 19, ingredient_id: 4, measurement_id: 5, quantity: 6.0)
RecipeIngredient.create(recipe_id: 19, ingredient_id: 5, measurement_id: 6, quantity: 7.0)
RecipeIngredient.create(recipe_id: 20, ingredient_id: 1, measurement_id: 7, quantity: 8.0)
RecipeIngredient.create(recipe_id: 20, ingredient_id: 2, measurement_id: 8, quantity: 3.0)
RecipeIngredient.create(recipe_id: 20, ingredient_id: 5, measurement_id: 9, quantity: 2.0)
RecipeIngredient.create(recipe_id: 21, ingredient_id: 4, measurement_id: 10, quantity: 4.0)
RecipeIngredient.create(recipe_id: 21, ingredient_id: 2, measurement_id: 1, quantity: 5.0)
RecipeIngredient.create(recipe_id: 21, ingredient_id: 3, measurement_id: 2, quantity: 6.0)
RecipeIngredient.create(recipe_id: 22, ingredient_id: 1, measurement_id: 3, quantity: 3.0)
RecipeIngredient.create(recipe_id: 22, ingredient_id: 1, measurement_id: 4, quantity: 3.0)

Rating.create(user_id: 1, recipe_id: 1, stars: 2.0)
Rating.create(user_id: 2, recipe_id: 1, stars: 3.0)
Rating.create(user_id: 3, recipe_id: 1, stars: 4.0)
Rating.create(user_id: 4, recipe_id: 2, stars: 5.0)
Rating.create(user_id: 5, recipe_id: 2, stars: 3.0)
Rating.create(user_id: 6, recipe_id: 2, stars: 2.0)
Rating.create(user_id: 4, recipe_id: 3, stars: 5.0)
Rating.create(user_id: 1, recipe_id: 3, stars: 1.0)
Rating.create(user_id: 2, recipe_id: 4, stars: 2.0)
Rating.create(user_id: 3, recipe_id: 4, stars: 3.0)
Rating.create(user_id: 4, recipe_id: 4, stars: 2.0)
Rating.create(user_id: 5, recipe_id: 4, stars: 2.0)
Rating.create(user_id: 6, recipe_id: 5, stars: 3.0)
Rating.create(user_id: 2, recipe_id: 5, stars: 4.0)
Rating.create(user_id: 2, recipe_id: 5, stars: 5.0)
Rating.create(user_id: 3, recipe_id: 5, stars: 3.0)
Rating.create(user_id: 4, recipe_id: 6, stars: 2.0)
Rating.create(user_id: 5, recipe_id: 6, stars: 5.0)
Rating.create(user_id: 6, recipe_id: 6, stars: 1.0)
Rating.create(user_id: 1, recipe_id: 7, stars: 2.0)
Rating.create(user_id: 2, recipe_id: 7, stars: 3.0)
Rating.create(user_id: 1, recipe_id: 7, stars: 2.0)
Rating.create(user_id: 6, recipe_id: 8, stars: 3.0)
Rating.create(user_id: 3, recipe_id: 8, stars: 4.0)
Rating.create(user_id: 1, recipe_id: 8, stars: 5.0)
Rating.create(user_id: 2, recipe_id: 8, stars: 3.0)
Rating.create(user_id: 3, recipe_id: 8, stars: 2.0)
Rating.create(user_id: 4, recipe_id: 8, stars: 5.0)
Rating.create(user_id: 5, recipe_id: 9, stars: 1.0)
Rating.create(user_id: 6, recipe_id: 9, stars: 2.0)
Rating.create(user_id: 2, recipe_id: 9, stars: 3.0)
Rating.create(user_id: 1, recipe_id: 10, stars: 2.0)
Rating.create(user_id: 1, recipe_id: 11, stars: 3.0)
Rating.create(user_id: 2, recipe_id: 11, stars: 4.0)
Rating.create(user_id: 3, recipe_id: 12, stars: 5.0)
Rating.create(user_id: 4, recipe_id: 12, stars: 3.0)
Rating.create(user_id: 5, recipe_id: 12, stars: 2.0)
Rating.create(user_id: 6, recipe_id: 12, stars: 5.0)
Rating.create(user_id: 6, recipe_id: 13, stars: 1.0)
Rating.create(user_id: 1, recipe_id: 13, stars: 2.0)
Rating.create(user_id: 1, recipe_id: 14, stars: 3.0)
Rating.create(user_id: 2, recipe_id: 14, stars: 2.0)
Rating.create(user_id: 3, recipe_id: 15, stars: 3.0)
Rating.create(user_id: 4, recipe_id: 16, stars: 2.0)
Rating.create(user_id: 5, recipe_id: 16, stars: 5.0)
Rating.create(user_id: 6, recipe_id: 16, stars: 1.0)
Rating.create(user_id: 1, recipe_id: 17, stars: 2.0)
Rating.create(user_id: 2, recipe_id: 17, stars: 3.0)
Rating.create(user_id: 1, recipe_id: 17, stars: 2.0)
Rating.create(user_id: 6, recipe_id: 18, stars: 3.0)
Rating.create(user_id: 1, recipe_id: 18, stars: 4.0)
Rating.create(user_id: 1, recipe_id: 18, stars: 5.0)
Rating.create(user_id: 2, recipe_id: 18, stars: 3.0)
Rating.create(user_id: 3, recipe_id: 18, stars: 2.0)
Rating.create(user_id: 4, recipe_id: 18, stars: 5.0)
Rating.create(user_id: 5, recipe_id: 19, stars: 1.0)
Rating.create(user_id: 6, recipe_id: 19, stars: 2.0)
Rating.create(user_id: 1, recipe_id: 19, stars: 3.0)
Rating.create(user_id: 1, recipe_id: 20, stars: 2.0)
Rating.create(user_id: 1, recipe_id: 21, stars: 3.0)
Rating.create(user_id: 2, recipe_id: 21, stars: 4.0)
Rating.create(user_id: 3, recipe_id: 22, stars: 5.0)
Rating.create(user_id: 4, recipe_id: 22, stars: 3.0)
Rating.create(user_id: 5, recipe_id: 22, stars: 2.0)
Rating.create(user_id: 6, recipe_id: 22, stars: 5.0)
Rating.create(user_id: 1, recipe_id: 22, stars: 1.0)
